evaluate_freq: 1  # Evaluation frequency
save_as: False # What to save the model as, if False, then it is saved as the wandb run name
verbose: 1  # 0: silent, 1: progress bar, 2: one line per epoch
device: "cuda"  # Options: "cuda", "mps", "cpu"
validation_size: 0.2  # Fraction of the training set to use as validation
dataloader_num_workers: 8
seed: 42
wandb:
  track: True
  project: "ModelInversion" # where current run will be loaded
  entity: "BreuerLab"
  track_features: False # ex. "[[0, 0], [0, 223], [112, 112], [223, 0], [223, 223]]"
  run_id: False # else give a wandb run id from which to continue training
  run_name: False
