name: "plug_and_play"
stylegan_path: "stylegan2-ada-pytorch/ffhq.pkl"

# From the pnp repo
candidates:
  num_candidates: 200
  candidate_search:
    search_space_size: 2000
    center_crop: null
    resize: 224
    horizontal_flip: true
    batch_size: 25
    truncation_psi: 0.5
    truncation_cutoff: 8

# For GAN
label_dim: 10
hyper:
  epochs: 3
  batch_size: 256
  n_critic: 5
discriminator:
  lr: 0.0001
  dropout: 0.3
  hidden_dim: [1024, 512, 256]
  negative_slope: 0.2 # Negative slope of the leaky ReLU function
generator:
  lr: 0.0001
  latent_dim: 100
  hidden_dim: [256, 512, 1024]
  negative_slope: 0.2 # Negative slope of the leaky ReLU function