# configuration/config.yaml
defaults:
  - model: cnn   # Yaml file describing which model and hyperparameters to use
  - dataset: FaceScrub # Yaml file with dataset specific parameters
  - training: default # Yaml file with training specific parameters
  - defense: no_defense # "drop_layer", "no_defense"

LL_terminate_on_end: False
LL_sleep_before_terminate: 3600 # number of seconds to sleep before terminating

