# configuration/config.yaml
defaults:
  - model: pretrained   # Yaml file describing which model and hyperparameters to use
  - dataset: FaceScrub # Yaml file with dataset specific parameters
  - training: default # Yaml file with training specific parameters
  - defense: no_defense # Yaml file with defense specific parameters

calculate_fisher: False # work in progress

