# configuration/config.yaml
defaults:
  - model: cnn   # Yaml file describing which model and hyperparameters to use
  - dataset: CelebA # Yaml file with dateset specific parameters
  - training: default # Yaml file with training specific parameters
  - defense: no_defense # "drop_layer", "no_defense"

