name: "LassoNet"
optimizer: "adam"
criterion: "crossentropy"
hotstart_model: False # Else give path to model
hyper:
  lr: 0.001
  epochs: 20
  batch_size: 256
  patience: 100
  linear_output_size: 256
