name: "SGLNN"
optimizer: "adam"
criterion: "crossentropy"
hotstart_model: False # Else give path to model
hyper:
  lr: 0.001
  epochs: 20
  batch_size: 256
  hidden_size: 100
  patience: 100
  gl_lmbda: 1
  sgl_alpha: 0.04 # See SGLNN paper Eqn. (15)

