# Peng et al. 2022 defense

name: "bido"
optimizer: "adam"
criterion: "crossentropy"
measure: "HSIC" # HSIC or COCO
ktype: "linear" # linear, gaussian, IMQ
hsic_training: True
hotstart_model: False # Else give path to model
root_path: "./"
config_dir: './config'
model_dir: './target_model'
hyper:
  lr: 0.001
  epochs: 20
  batch_size: 256
  patience: 100
  linear_output_size: 256
