name: "CNN"
optimizer: "adam"
criterion: "crossentropy"
flatten: False # whether or not input needs to be flattened before passing to model
hotstart_model: False # Else give path to model
hyper:
  lr: 0.001
  epochs: 20
  batch_size: 256
  n_neurons: 64  
  n_depth: 2
  dropout: 0.0
  stride: 1
  kernel_size: 3
  patience: 10
  linear_output_size: 256
  beta2: 0.999
