name: "DropLayer"
architecture: "MLP"
optimizer: "adam"
criterion: "crossentropy"
hotstart_model: False # Else give path to model
hyper:
  lr: 0.001
  epochs: 20
  batch_size: 256
  patience: 20
  linear_output_size: 256
  n_neurons: 64  
  n_depth: 2
  dropout: 0.0
  kernel_size: 3
  stride: 1


