name: "MLP"
optimizer: "adam"
criterion: "crossentropy"
flatten: True
hotstart_model: False # Else give path to model
hyper:
  lr: 0.001
  epochs: 10
  batch_size: 256
  n_neurons: 64  
  n_depth: 2
  dropout: 0.0
  kernel_size: 3
  patience: 10
