name: "PreTrainedClassifier"
architecture: "resnet18" # Options: resnet18, resnet152, inception
pretrained: True
optimizer: "adam"
criterion: "crossentropy"
hotstart_model: False # Else give path to model
flatten: False # whether or not input needs to be flattened before passing to model
hyper:
  lr: 0.001
  epochs: 20
  batch_size: 256
  patience: 20
  beta2: 0.999
