# conf/config.yaml
defaults:
  - model: lasso_net   # Yaml file describing which model and hyperparameters to use
  - dataset: MNIST  # Yaml file with dateset specific parameters
  - training: default # Yaml file with training specific parameters

