# conf/config.yaml
defaults:
  - attack: plug_and_play   # Yaml file describing which model and hyperparameters to use
  - dataset: MNIST  # Yaml file with dateset specific parameters
  - running: default # Yaml file with training specific parameters