evaluate_freq: 1  # Evaluation frequency
display_step: 189
save_as: "gan" # What to save the model as, if False, then it is saved as the wandb run name
verbose: 1  # 0: silent, 1: progress bar, 2: one line per epoch
device: "mps"  # Options: "cuda", "mps", "cpu"
validation_size: 0.2  # Fraction of the training set to use as validation
wandb:
  track: True
  project: "ModelInversion"
  entity: "BreuerLab"