# conf/config.yaml
defaults:
  - model: plug_and_play   # Yaml file describing which model and hyperparameters to use
  - dataset: MNIST  # Yaml file with dateset specific parameters
  - training: default # Yaml file with training specific parameters

target_wandb_id: po6xckc2 
target_path: False