evaluate_freq: 1  # Evaluation frequency
save_as: "model.pth"
verbose: 1  # 0: silent, 1: progress bar, 2: one line per epoch
device: "cpu"  # Options: "cuda", "mps", "cpu"
validation_size: 0.1  # Fraction of the training set to use as validation
wandb:
  track: False
  project: "ModelInversion"
  entity: "BreuerLab"